title: tech blog (memo)
theme: jekyll-theme-merlot
themexxx1: jekyll-theme-minimal
themexxx2: jekyll-theme-dinky
themexxx3: jekyll-theme-merlot
themexxx4: jekyll-theme-modernist
themexxx5: jekyll-theme-hacker
