#!/bin/sh
echo ""
echo ""
echo "Start my pre-commit hook .... update index.md ..."
echo ""
echo ""

# update_index.sh スクリプトを実行
bash update_index.sh

# 更新された index.md をコミットに追加
cp index.md README.md
git add index.md
git add README.md